const text = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas at augue quis lacus aliquam tristique. Quisque vitae odio non purus pretium iaculis vel et lectus. Mauris nec dui nec libero posuere porta ac eget tellus. Phasellus hendrerit leo convallis magna mattis, eu posuere enim viverra. Vivamus sit amet nulla nulla. Praesent commodo posuere nisl, dignissim aliquam neque. In tristique lacinia elementum. Integer nisi eros, pulvinar tincidunt ante eu, aliquam pharetra est. Nam augue eros, tempor eget feugiat vestibulum, rhoncus at nunc. Phasellus viverra sollicitudin metus, sit amet varius urna. Praesent ut convallis lorem.",
  "Nam placerat arcu augue, eu fermentum mi malesuada quis. Donec elementum pharetra sem in mattis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas scelerisque arcu mi, vel lacinia nulla dapibus ut. Curabitur ornare orci eget dolor pellentesque, id imperdiet tellus porta. Aenean odio lectus, interdum id consequat sit amet, faucibus eu nisl. Aliquam non sem ante.",
  "Sed in tristique ligula. Nam elit nisl, euismod a elit in, semper auctor mi. Praesent tristique condimentum laoreet. Suspendisse sapien erat, egestas at faucibus ac, gravida rutrum sem. Nunc dolor risus, auctor vitae eros eget, luctus finibus nibh. Vestibulum sapien est, commodo in nibh ut, tristique tristique dui. In molestie tristique lacus ac scelerisque. Etiam et nulla ut risus efficitur mollis sed eget neque. Donec dolor velit, hendrerit non ultricies ut, luctus et ante. Phasellus pharetra ligula at pharetra euismod. Suspendisse potenti. Cras eu ullamcorper leo, a sodales libero. Vestibulum in sapien quis leo fringilla placerat ac sit amet purus. Integer imperdiet pellentesque risus, et pretium odio imperdiet vitae. Aenean feugiat, dolor quis auctor suscipit, odio mi elementum nibh, id lacinia ipsum leo vel dolor.",
  "Maecenas tincidunt, ligula ut vulputate semper, risus mi interdum ex, in volutpat sem dui a enim. Curabitur nec diam vitae tellus gravida dictum at eget massa. Curabitur fermentum, metus et vulputate mollis, velit nulla iaculis nulla, quis tempus massa dui a erat. Ut interdum turpis sapien, quis facilisis est convallis a. Duis rhoncus dui vitae ligula tincidunt, at ultrices purus faucibus. Pellentesque eget mauris sed augue suscipit porta sed non ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent vulputate quam velit, vel ultricies lectus fermentum at. Integer eget ipsum vitae tellus tristique congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi faucibus neque sit amet leo consequat vulputate. In commodo augue nec est porta imperdiet. Vivamus ac lectus nec diam molestie lobortis nec eget ex. Donec sollicitudin diam eu rutrum dignissim. Cras at nisi aliquet, dictum arcu at, aliquet velit. Pellentesque dictum mi nec sapien dictum mattis.",
  "Nam aliquet lectus mauris, nec gravida eros faucibus eget. Vivamus sed libero ornare, tincidunt tortor vel, vulputate lectus. Aliquam erat volutpat. Phasellus sem nulla, efficitur et sem et, venenatis congue nisi. Nullam euismod massa elit, et rutrum urna egestas vel. Etiam scelerisque hendrerit pretium. Nunc tempus magna dolor, eget dapibus metus tincidunt ultrices. Fusce egestas pulvinar lobortis. In vitae dictum arcu. Cras vel pellentesque neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "Curabitur commodo dolor lacus, vitae accumsan quam vulputate non. Praesent orci ipsum, posuere et pellentesque nec, dignissim nec lorem. Etiam ultricies gravida tempus. Pellentesque bibendum ornare mauris, vitae bibendum libero pharetra aliquam. Donec eleifend ullamcorper turpis, id efficitur mi finibus ut. Aliquam non nisl est. Fusce eleifend accumsan pretium. Sed vitae euismod quam. Ut non ultricies lectus. Maecenas dignissim ullamcorper mauris in tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sollicitudin tincidunt interdum. Cras venenatis suscipit risus, at aliquam turpis posuere a. Praesent eleifend et mauris eget vulputate. Sed nisl ipsum, rhoncus nec rhoncus a, vehicula ac sapien.",
  "Morbi nec ligula quis sem volutpat congue id sed mauris. Pellentesque et sem tincidunt, sagittis leo accumsan, pulvinar massa. Cras ac lacinia tellus. Cras consequat massa vitae nulla finibus, et lacinia ex porta. Duis porttitor facilisis erat, in lacinia urna fringilla a. In sit amet urna vel lacus dignissim gravida. Proin convallis rhoncus nibh, sit amet varius felis fermentum sit amet. Donec volutpat magna non neque fermentum tristique. Cras lacinia placerat massa, sed volutpat odio interdum in. Cras at tempor ante. Praesent laoreet quis ipsum ut consequat. Etiam rhoncus risus ut pulvinar aliquam. Donec nec quam condimentum, bibendum leo ut, gravida neque. Cras quis efficitur elit, quis ornare erat.",
  "Integer est felis, eleifend id velit a, consequat malesuada elit. Aliquam erat volutpat. Vestibulum bibendum ullamcorper feugiat. Nam dui justo, mollis sodales mi in, vulputate euismod leo. Nulla nec nibh eget odio fermentum ullamcorper. Cras euismod turpis quam, quis ornare libero ornare nec. Nullam sodales leo sit amet mollis auctor. Suspendisse maximus gravida maximus. Suspendisse hendrerit ante at ultricies lobortis. In suscipit, tellus nec placerat porta, lorem dui efficitur quam, eu pellentesque ipsum erat non diam. Sed euismod mi sit amet ultricies rutrum. Sed elementum quam eu finibus interdum. Nam volutpat venenatis augue, ut vestibulum metus aliquam in. Integer non finibus dui, quis viverra justo.",
];

export default text;
